[theme]
primaryColor = "#1d4ed8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8faff"
textColor = "#1f2937"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
